version: '3.8'

services:
  auth:
    image: auth-service
    build: .
    ports:
      - "80:8080"

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: step
      POSTGRES_PASSWORD: step
      POSTGRES_DB: auth
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: redis
    volumes:
      - redis_data:/data

  mosquitto:
    image: mosquitto_auth
    container_name: mosquitto
    ports:
      - "41031:1883"
      - "9001:9001"  # Для WebSocket (если нужно)
    volumes:
      - ./mosquitto/config:/etc/mosquitto
      - ./mosquitto/data:/etc/mosquitto/data
      - ./mosquitto/log:/etc/mosquitto/log
      - ./mosquitto/plugins:/etc/mosquitto/plugins

volumes:
  postgres_data:
  redis_data:
